<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}
	
	acf_add_local_field_group( array(
		'key' => 'group_65ece867815d4',
		'title' => 'Account Menu',
		'fields' => array(
			array(
				'key' => 'field_65ece8671a334',
				'label' => 'Menu',
				'name' => 'menu',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'automatic' => '(Automatic)',
					'default' => 'Default (2 Items)',
				),
				'default_value' => 'automatic',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-account-pages/account-menu',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'ACF Block (Account Menu)',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_66195ca4d8b92',
		'title' => 'Account Page',
		'fields' => array(
			array(
				'key' => 'field_66195ca4a158a',
				'label' => 'Protection',
				'name' => 'protect_page',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'Prevent access unless this page is in the user\'s active menu.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'message' => 'Protect this page',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'account-page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_65e8d2015bad4',
		'title' => 'Account Pages - General Settings',
		'fields' => array(
			array(
				'key' => 'field_65e8d201f793d',
				'label' => 'Menus',
				'name' => 'menus',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'The first menu that meets all conditions will be used for the account page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'pagination' => 0,
				'min' => 1,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_65e8d28df793f',
						'label' => 'Menu Name',
						'name' => 'menu_name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_65e8d201f793d',
					),
					array(
						'key' => 'field_65e8d298f7940',
						'label' => 'Menu Slug',
						'name' => 'menu_slug',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_65e8d201f793d',
					),
					array(
						'key' => 'field_65e8d21ff793e',
						'label' => 'Condition(s)',
						'name' => 'conditions',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'logged_in' => 'Logged in',
							'logged_out' => 'Logged out',
							'admin' => 'Administrator',
							'not_admin' => 'Not Administrator',
							'never_show' => 'Never Show Automatically',
						),
						'default_value' => array(
						),
						'return_format' => 'value',
						'multiple' => 1,
						'allow_null' => 1,
						'ui' => 1,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_65e8d201f793d',
					),
					array(
						'key' => 'field_65e8d2b2f7941',
						'label' => 'Menu Items',
						'name' => 'menu_items',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'min' => 1,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Row',
						'rows_per_page' => 20,
						'parent_repeater' => 'field_65e8d201f793d',
						'sub_fields' => array(
							array(
								'key' => 'field_65e8d380f7946',
								'label' => 'Type',
								'name' => 'type',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'page' => 'Page',
									'login' => 'Sign in',
									'logout' => 'Sign out',
									'custom' => 'Custom link',
								),
								'default_value' => 'page',
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_65e8d2b2f7941',
							),
							array(
								'key' => 'field_65e8d46343a36',
								'label' => 'Menu Item',
								'name' => 'menu_item',
								'aria-label' => '',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => 'acf-hide-label acf-no-border acf-no-padding',
									'id' => '',
								),
								'layout' => 'block',
								'parent_repeater' => 'field_65e8d2b2f7941',
								'sub_fields' => array(
									array(
										'key' => 'field_65e8d2bcf7942',
										'label' => 'Account Page',
										'name' => 'post_id',
										'aria-label' => '',
										'type' => 'post_object',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_65e8d380f7946',
													'operator' => '==',
													'value' => 'page',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => 'acf-hide-label',
											'id' => '',
										),
										'post_type' => array(
											0 => 'account-page',
										),
										'post_status' => '',
										'taxonomy' => '',
										'return_format' => 'id',
										'multiple' => 0,
										'allow_null' => 0,
										'bidirectional' => 0,
										'ui' => 1,
										'bidirectional_target' => array(
										),
									),
									array(
										'key' => 'field_65e8d70311b78',
										'label' => 'Custom Title',
										'name' => 'custom_title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_65e8d2d7f7943',
													'operator' => '==',
													'value' => 'custom_title',
												),
											),
											array(
												array(
													'field' => 'field_65e8d380f7946',
													'operator' => '==',
													'value' => 'custom',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => 'acf-hide-label',
											'id' => '',
										),
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => 'Custom Title',
										'prepend' => 'Title',
										'append' => '',
									),
									array(
										'key' => 'field_65e8d3b8f7947',
										'label' => 'Custom URL',
										'name' => 'custom_url',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_65e8d380f7946',
													'operator' => '==',
													'value' => 'custom',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => 'acf-hide-label',
											'id' => '',
										),
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => 'https://example.org/',
										'prepend' => 'URL',
										'append' => '',
									),
									array(
										'key' => 'field_65eceaa0c2601',
										'label' => 'Conditions',
										'name' => 'conditions',
										'aria-label' => '',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_65e8d2d7f7943',
													'operator' => '==',
													'value' => 'conditional',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => 'acf-hide-label acf-no-border acf-no-padding',
											'id' => '',
										),
										'choices' => array(
											'logged_in' => 'Logged in',
											'logged_out' => 'Logged out',
											'admin' => 'Administrator',
											'not_admin' => 'Not Administrator',
										),
										'default_value' => array(
										),
										'return_format' => 'value',
										'multiple' => 1,
										'allow_null' => 1,
										'ui' => 1,
										'ajax' => 0,
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_65e8d2d7f7943',
								'label' => 'Options',
								'name' => 'options',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'hidden' => 'Hidden (still accessible)',
									'custom_title' => 'Custom Title',
									'conditional' => 'Conditional',
								),
								'default_value' => array(
								),
								'return_format' => 'value',
								'multiple' => 1,
								'allow_null' => 1,
								'ui' => 1,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_65e8d2b2f7941',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'account-page-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );